# $Id$

BEGIN {
	print "% $Id$";
}

/^# Generated by/ {
	print "% " $0 "\n";
	print "-define(XMPP_KNOWN_ATTRS, [";
}

/^[^#]/ {
	print "  '" $1 "',";
}

END {
	print "  '$end_of_table'";
	print "]).";
}
