/* $Id$ */

var fso, fd, line, re;

if (WScript.Arguments.length  != 1) {
	WScript.Echo("Syntax: cscript " +
	    "exmpp_known_elems.hrl.js <exmpp_known_elems.hrl.in>");
} else {
	/* Open the input file for reading (1). */
	fso = new ActiveXObject("Scripting.FileSystemObject");
	fd = fso.OpenTextFile(WScript.Arguments.Item(0), 1, false);

	/* This regexp filters out comments. */
	re_start = /^# Generated by/;
	re = /^[^#]/;

	/* Fill in the Erlang header file. */
	WScript.Echo("% $Id$");

	while (!fd.AtEndOfStream) {
		line = fd.ReadLine();
		if (line.match(re_start)) {
			WScript.Echo("% " + line + "\n");
			WScript.Echo("-define(XMPP_KNOWN_ELEMS, [");
		}
		if (line.match(re))
			WScript.Echo("  '" + line + "',");
	}
	WScript.Echo("  '$end_of_table'");
	WScript.Echo("]).");

	/* Done! */
	fd.close();
}
