/* $Id$ */

#ifndef EXMPP_COMPRESS_H
#define	EXMPP_COMPRESS_H 1

#include "exmpp_driver.h"

/* Return codes. */
enum {
	RET_OK = 0,
	RET_ERROR
};

/* Control operations. */
enum {
	COMMAND_SET_COMPRESS_METHOD = 1,
	COMMAND_SET_COMPRESS_LEVEL,
	COMMAND_PREPARE_COMPRESS,
	COMMAND_PREPARE_UNCOMPRESS,
	COMMAND_COMPRESS,
	COMMAND_UNCOMPRESS,
	COMMAND_SVN_REVISION
};

#endif /* !defined(EXMPP_COMPRESS_H) */
