{
	[
		'./core/*',
		'./exmpp_known_nss',
		'./exmpp_known_elems',
		'./exmpp_known_attrs',
		'./network/*',
		'./client/*',
		'./server/*'
	],
	[
		debug_info, {d, debug}, report_warnings, {warn_format, 1}, warn_export_vars, warn_shadow_vars, warn_unused_import, {d, 'HAVE_EXPAT'}, {d, 'HAVE_LIBXML2'}, {d, 'HAVE_OPENSSL'}, {d, 'HAVE_ZLIB'},
		{outdir, "./../ebin"},
		{i, "../include"},
		{i, "../include"}
	]
}.

% vim:ft=erlang:
